import { Inter } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "@/Contexts/ContextProvider";
import ToastProvider from "@/Providers/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hostell",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider>
          <ContextProvider>{children}</ContextProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
